### ISSUE TITLE
Fail to install 

### ISSUE THREAD

**Issue by dihuangdh** [tymoteuszb/smooth-sampler#1]
Hi, @tymoteuszb @JingwenWang95 

I got the following errors by `pip install git+https://github.com/tymoteuszb/smooth-sampler`

    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no suitable user-defined conversion from "const at::TensorBase" to "const at::Tensor" exists
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no suitable user-defined conversion from "const at::TensorBase" to "const at::Tensor" exists
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "smooth_sampler_kernel" matches the argument list
                argument types are: (int, <error-type>, <error-type>, <error-type>, at::native::detail::GridSamplerPadding, __nv_bool, __nv_bool)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "smooth_sampler_kernel" matches the argument list
                argument types are: (int64_t, <error-type>, <error-type>, <error-type>, at::native::detail::GridSamplerPadding, __nv_bool, __nv_bool)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no suitable user-defined conversion from "const at::TensorBase" to "const at::Tensor" exists
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no suitable user-defined conversion from "const at::TensorBase" to "const at::Tensor" exists
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no suitable user-defined conversion from "const at::TensorBase" to "const at::Tensor" exists
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "smooth_sampler_kernel" matches the argument list
                argument types are: (int, <error-type>, <error-type>, <error-type>, at::native::detail::GridSamplerPadding, __nv_bool, __nv_bool)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "smooth_sampler_kernel" matches the argument list
                argument types are: (int64_t, <error-type>, <error-type>, <error-type>, at::native::detail::GridSamplerPadding, __nv_bool, __nv_bool)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no suitable user-defined conversion from "const at::TensorBase" to "const at::Tensor" exists
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no suitable user-defined conversion from "const at::TensorBase" to "const at::Tensor" exists
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no suitable user-defined conversion from "const at::TensorBase" to "const at::Tensor" exists
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "smooth_sampler_kernel" matches the argument list
                argument types are: (int, <error-type>, <error-type>, <error-type>, at::native::detail::GridSamplerPadding, __nv_bool, __nv_bool)
    
    /tmp/pip-req-build-702sk3li/smooth_sampler/csrc/smooth_sampler_kernel.cu(630): error: no instance of function template "at::cuda::detail::getTensorInfo" matches the argument list
                argument types are: (const at::TensorBase)`

**Comment by tym-b** [comment]
Hi @dihuangdh,

Could you provide the Pytorch version you are using?

**Comment by dihuangdh** [comment]
Hi @tymoteuszb , thanks for your reply.

I am using PyTorch 10.0. 

I noticed this repo is built upon PyTorch 1.2. I was just wondering if a different version of PyTorch could use this repo. 

Since lots of users are not using PyTorch 1.2, I think making the smooth-sampler capable of other PyTorch versions is a potentially important future update (but it's ok to keep the current state if this repo is just for reproducing the GO-surf results). 

Besides, is it possible for you to give a figure show the speed comparison between your implementation and [https://github.com/pytorch/pytorch/issues/34704](https://gessisc.com/click?redirect=https%3A%2F%2Fgithub.com%2Fpytorch%2Fpytorch%2Fissues%2F34704&dID=1656901362836&linkName=https://github.com/pytorch/pytorch/issues/34704)  (both forward and backward).

**Comment by JingwenWang95** [comment]
Hi @dihuangdh, do you mean PyTorch 1.10? Actually our grid sampler is built with and tested under PyTorch 1.11, but it shouldn't have so much difference for other versions. Anyways, thanks for your feedback! We will do more testings with other versions. 

Also, have you tried cloning this repo and running `python setup.py install` instead of using `pip` and see what error messages it gives you? And regarding the speed comparson, we will do some benchmarking on run-time and memory usage and compare with the PyTorch implementation you mentioned!

**Comment by dihuangdh** [comment]
Sorry for the typo; I am using PyTorch 1.10.

I will try `python setup.py install` and let you know if there is any problem.

**Comment by dihuangdh** [comment]
Solved by using PyTorch 1.11
